package oop;

public class Runner {
    public static void main(String[] args) {
        Dog dog=new Dog();
        dog.bark();//Dogs bark...
        dog.eat();//Animals eat...
        dog.feedWithMilk();//Mammals feeds their babies with milk...

        Bird bird=new Bird();
        bird.tweet();//Birds tweet...
        bird.drink();//Animals drink...
    }
}
